
import React, { useEffect, useState } from "react";
import axios from "axios"
import { useAuth } from "../../context/AuthContext.jsx";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function HospitalReports() {
    const { user } = useAuth();
    const hospitalId = user?.hospitalId || localStorage.getItem("hospitalId");
    const [donations, setDonations] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (hospitalId) fetchReport();
    }, [hospitalId]);

    const fetchReport = async () => {
        try {
            setLoading(true);
            const res = await axios.get(
                `http://localhost:8080/api/donations/byHospital/${hospitalId}`
            );
            setDonations(res.data);
        } catch (err) {
            console.error("Error fetching reports:", err);
        } finally {
            setLoading(false);
        }
    };


    const downloadPDF = () => {
        const doc = new jsPDF();
        doc.setFontSize(16);
        doc.text(" Hospital Donation Report", 14, 20);
        doc.setFontSize(11);
        doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 28);

        const tableData = donations.map((d, i) => [
            i + 1,
            d.donorName,
            d.bloodGroup,
            d.bloodQuantity,
            d.donationDate,
            d.donationTime,
            d.status,
        ]);

        autoTable(doc, {
            startY: 35,
            head: [["#", "Donor", "Blood Group", "Units", "Date", "Time", "Status"]],
            body: tableData,
            theme: "striped",
            headStyles: { fillColor: [255, 0, 0] },
            styles: { halign: "center" },
        });

        doc.text("Generated by BloodLink System", 14, doc.lastAutoTable.finalY + 10);
        doc.save("Hospital_Report.pdf");
    };


    const countByStatus = (status) =>
        donations.filter((d) => d.status === status).length;

    if (loading) return <div>Loading reports...</div>;

    return (
        <div className="w-full bg-white p-6 rounded-xl shadow-md">
            <div className="flex justify-between items-center mb-4">
                <h2 className="text-xl font-bold text-red-600">📊 Donation Reports</h2>
                <button
                    onClick={downloadPDF}
                    className="bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700"
                >
                    Download PDF
                </button>
            </div>

            <div className="grid grid-cols-3 gap-4 mb-6">
                <div className="p-4 bg-green-100 rounded-lg text-center">
                    <h3 className="font-bold text-green-700 text-lg">Completed</h3>
                    <p className="text-2xl">{countByStatus("COMPLETED")}</p>
                </div>

                <div className="p-4 bg-yellow-100 rounded-lg text-center">
                    <h3 className="font-bold text-yellow-700 text-lg">Pending</h3>
                    <p className="text-2xl">{countByStatus("PENDING")}</p>
                </div>

                <div className="p-4 bg-red-100 rounded-lg text-center">
                    <h3 className="font-bold text-red-700 text-lg">Rejected</h3>
                    <p className="text-2xl">{countByStatus("REJECTED")}</p>
                </div>
            </div>

            <div className="overflow-x-auto">
                <table className="min-w-full text-sm text-left border">
                    <thead className="bg-red-100">
                    <tr>
                        <th className="px-4 py-2 border">#</th>
                        <th className="px-4 py-2 border">Donor</th>
                        <th className="px-4 py-2 border">Blood Group</th>
                        <th className="px-4 py-2 border">Units</th>
                        <th className="px-4 py-2 border">Date</th>
                        <th className="px-4 py-2 border">Time</th>
                        <th className="px-4 py-2 border">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    {donations.length > 0 ? (
                        donations.map((don, index) => (
                            <tr key={don.donationId} className="border-b hover:bg-gray-50">
                                <td className="px-4 py-2 border">{index + 1}</td>
                                <td className="px-4 py-2 border">{don.donorName}</td>
                                <td className="px-4 py-2 border font-bold">
                                    {don.bloodGroup}
                                </td>
                                <td className="px-4 py-2 border">{don.bloodQuantity}</td>
                                <td className="px-4 py-2 border">{don.donationDate}</td>
                                <td className="px-4 py-2 border">{don.donationTime}</td>
                                <td className="px-4 py-2 border">{don.status}</td>
                            </tr>
                        ))
                    ) : (
                        <tr>
                            <td className="p-2 border text-center" colSpan="7">
                                No donation records found.
                            </td>
                        </tr>
                    )}
                    </tbody>
                </table>
            </div>
        </div>
    );
}

// import React from "react";
//
// const Reports = () => {
//     return (
//         <div>
//             <h1 className="text-2xl text-center font-bold mb-4">Reports</h1>
//             <p className="text-gray-600">Generate and view activity reports.
//                 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus sequi officiis cum rerum, odit doloribus. Provident dolores et dolor nam quaerat neque maiores qui saepe. Labore blanditiis laudantium provident expedita.
//                 Inventore impedit similique, maiores optio quibusdam dicta, cumque provident, ut harum id molestias natus esse! Ex consectetur nostrum accusamus quam! Eius eveniet reiciendis accusamus harum asperiores facere et ipsam delectus.
//             </p>
//         </div>
//     );
// };
//
// export default Reports;
